# Generated by Django 4.0.1 on 2022-01-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.CharField(max_length=80)),
                ('priority', models.CharField(choices=[('0', 'Sem Problemas'), ('1', 'Normal'), ('2', 'Urgente'), ('3', 'Muito Urgente   ')], max_length=1)),
            ],
        ),
    ]
