# Generated by Django 4.0.1 on 2022-01-31 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_event_author_alter_event_date_alter_event_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='author',
            new_name='autor',
        ),
    ]
