# Generated by Django 4.0.2 on 2022-02-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0006_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hour',
            field=models.TimeField(default=1, verbose_name='Horário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
