# Generated by Django 4.0.2 on 2022-02-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0007_event_hour_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hour',
            field=models.TimeField(auto_now_add=True, verbose_name='Horário'),
        ),
    ]
