# Generated by Django 4.0.2 on 2022-02-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0008_alter_event_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hour',
            field=models.TimeField(verbose_name='Horário'),
        ),
    ]
