# Generated by Django 4.0.2 on 2022-02-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0009_alter_event_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hour',
        ),
    ]
