# Generated by Django 4.0.2 on 2022-02-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0010_remove_event_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hour',
            field=models.TimeField(default=1, verbose_name='Horário'),
            preserve_default=False,
        ),
    ]
