# Generated by Django 4.0.2 on 2022-02-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0011_event_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hour',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(verbose_name='Data'),
        ),
    ]
